App Store Create New Access Token Endpoint
DudaDev/partner-api pull request #178
Opened 2024-02-21 22:09 UTC by PayEstakhri

- Cleaned up tokens.ts file
- Cleaned up types.ts file
- Cleaned up tokens.tests.file

2024-02-29 17:28 UTC, jhummel requested changes

2024-02-29 17:28 UTC, jhummel commented on src/lib/apps/tokens/Tokens.ts
> +  create = APIEndpoint<TokenRequest<Types.RefreshTokenPayload>, Types.RefreshTokenResponse>({
You actually don't need a token to refresh the authorization code, since this call doesn't affect client sites.

2024-02-29 17:28 UTC, jhummel commented on src/lib/apps/tokens/Tokens.ts
> +    headerOptions: {
Not needed, see above

2024-02-29 17:28 UTC, jhummel commented on src/lib/apps/tokens/types.ts
> +  refresh_token?: string
This is required, I believe.

2024-02-29 17:28 UTC, jhummel commented on tests/app/token.tests.ts
> +        'x-duda-access-token': `Bearer ${token}`
Only the basic auth is needed for this request, not the x-duda-access-token. Can revert.

2024-02-29 21:12 UTC, PayEstakhri reviewed
resolved

2024-03-01 20:51 UTC, jhummel approved these changes

2024-03-01 20:51 UTC, merged